### Importing the libraries

In [22]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [23]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [24]:
dataset = pd.read_csv('tic-tac-toe.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [25]:
print(X)

[['x' 'x' 'x' ... 'x' 'o' 'o']
 ['x' 'x' 'x' ... 'o' 'x' 'o']
 ['x' 'x' 'x' ... 'o' 'o' 'x']
 ...
 ['o' 'x' 'o' ... 'x' 'o' 'x']
 ['o' 'x' 'o' ... 'x' 'o' 'x']
 ['o' 'o' 'x' ... 'o' 'x' 'x']]


In [26]:
print(y)

['positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'posit

### Encoding categorical data

Label Encoding the class ("positive / negative") column

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [28]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

One Hot Encoding "x, o & b"

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1, 2, 3, 4, 5, 6, 7, 8])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [30]:
print(X)

[[0. 0. 1. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 1.]]


### Splitting the dataset into the Training set and Test set

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [33]:
print(X_train)

[[-0.52599113  1.40731828 -0.90048582 ...  1.91591537 -0.72728407
  -0.88631134]
 [ 1.90117275 -0.71057131 -0.90048582 ... -0.52194372  1.37497856
  -0.88631134]
 [-0.52599113 -0.71057131  1.11051166 ...  1.91591537 -0.72728407
  -0.88631134]
 ...
 [-0.52599113 -0.71057131  1.11051166 ...  1.91591537 -0.72728407
  -0.88631134]
 [ 1.90117275 -0.71057131 -0.90048582 ... -0.52194372 -0.72728407
   1.1282717 ]
 [-0.52599113 -0.71057131  1.11051166 ... -0.52194372  1.37497856
  -0.88631134]]


In [34]:
print(X_test)

[[ 1.90117275 -0.71057131 -0.90048582 ... -0.52194372  1.37497856
  -0.88631134]
 [ 1.90117275 -0.71057131 -0.90048582 ...  1.91591537 -0.72728407
  -0.88631134]
 [-0.52599113 -0.71057131  1.11051166 ... -0.52194372 -0.72728407
   1.1282717 ]
 ...
 [-0.52599113  1.40731828 -0.90048582 ... -0.52194372 -0.72728407
   1.1282717 ]
 [ 1.90117275 -0.71057131 -0.90048582 ... -0.52194372  1.37497856
  -0.88631134]
 [-0.52599113  1.40731828 -0.90048582 ...  1.91591537 -0.72728407
  -0.88631134]]


## Part 2 - Building the ANN

### Initializing the ANN

In [35]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [36]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### Adding the second hidden layer

In [37]:
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))

### Adding the output layer

In [38]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [39]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [40]:
ann.fit(X_train, y_train, batch_size = 22, epochs = 100)

Epoch 1/100
35/35 [==============================] - 0s 902us/step - loss: 0.7824 - accuracy: 0.4843
Epoch 2/100
35/35 [==============================] - 0s 838us/step - loss: 0.6770 - accuracy: 0.5679
Epoch 3/100
35/35 [==============================] - 0s 860us/step - loss: 0.6283 - accuracy: 0.6214
Epoch 4/100
35/35 [==============================] - 0s 898us/step - loss: 0.5997 - accuracy: 0.6527
Epoch 5/100
35/35 [==============================] - 0s 917us/step - loss: 0.5785 - accuracy: 0.6684
Epoch 6/100
35/35 [==============================] - 0s 875us/step - loss: 0.5597 - accuracy: 0.6789
Epoch 7/100
35/35 [==============================] - 0s 879us/step - loss: 0.5425 - accuracy: 0.6854
Epoch 8/100
35/35 [==============================] - 0s 920us/step - loss: 0.5269 - accuracy: 0.7063
Epoch 9/100
35/35 [==============================] - 0s 956us/step - loss: 0.5109 - accuracy: 0.7311
Epoch 10/100
35/35 [==============================] - 0s 956us/step - loss: 0.4970 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [41]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]

### Making the Confusion Matrix

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred)*100))

[[ 71   3]
 [  0 118]]
Accuracy: 98.44%
